package com.graveyard.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// Color roles from the YAML front matter in DESIGN.md.
val surfaceLight = Color(0xFFF7F9FF)
val surfaceDimLight = Color(0xFFD7DAE0)
val surfaceBrightLight = Color(0xFFF7F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F4F9)
val surfaceContainerLight = Color(0xFFEBEEF3)
val surfaceContainerHighLight = Color(0xFFE5E8EE)
val surfaceContainerHighestLight = Color(0xFFE0E3E8)
val onSurfaceLight = Color(0xFF181C20)
val onSurfaceVariantLight = Color(0xFF414750)
val inverseSurfaceLight = Color(0xFF2D3135)
val inverseOnSurfaceLight = Color(0xFFEEF1F6)
val outlineLight = Color(0xFF717782)
val outlineVariantLight = Color(0xFFC1C7D2)
val surfaceTintLight = Color(0xFF0061A4)
val primaryLight = Color(0xFF00497D)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF0061A4)
val onPrimaryContainerLight = Color(0xFFC0DBFF)
val inversePrimaryLight = Color(0xFF9FCAFF)
val secondaryLight = Color(0xFF535F70)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD7E3F8)
val onSecondaryContainerLight = Color(0xFF596576)
val tertiaryLight = Color(0xFF52405F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF6B5778)
val onTertiaryContainerLight = Color(0xFFE9D0F7)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val primaryFixedLight = Color(0xFFD1E4FF)
val primaryFixedDimLight = Color(0xFF9FCAFF)
val onPrimaryFixedLight = Color(0xFF001D36)
val onPrimaryFixedVariantLight = Color(0xFF00497D)
val secondaryFixedLight = Color(0xFFD7E3F8)
val secondaryFixedDimLight = Color(0xFFBBC7DB)
val onSecondaryFixedLight = Color(0xFF101C2B)
val onSecondaryFixedVariantLight = Color(0xFF3C4858)
val tertiaryFixedLight = Color(0xFFF3DAFF)
val tertiaryFixedDimLight = Color(0xFFD6BEE4)
val onTertiaryFixedLight = Color(0xFF251431)
val onTertiaryFixedVariantLight = Color(0xFF523F5F)
val backgroundLight = Color(0xFFF7F9FF)
val onBackgroundLight = Color(0xFF181C20)
val surfaceVariantLight = Color(0xFFE0E3E8)
// The documents do not specify a scrim color; use the standard black scrim.
val scrimLight = Color(0xFF000000)

// Color roles from the YAML front matter in DESIGN_DARK.md.
val surfaceDark = Color(0xFF111318)
val surfaceDimDark = Color(0xFF111318)
val surfaceBrightDark = Color(0xFF37393F)
val surfaceContainerLowestDark = Color(0xFF0C0E13)
val surfaceContainerLowDark = Color(0xFF1A1B21)
val surfaceContainerDark = Color(0xFF1E2025)
val surfaceContainerHighDark = Color(0xFF282A2F)
val surfaceContainerHighestDark = Color(0xFF33353A)
val onSurfaceDark = Color(0xFFE2E2E9)
val onSurfaceVariantDark = Color(0xFFC2C7D0)
val inverseSurfaceDark = Color(0xFFE2E2E9)
val inverseOnSurfaceDark = Color(0xFF2E3036)
val outlineDark = Color(0xFF8C919A)
val outlineVariantDark = Color(0xFF42474F)
val surfaceTintDark = Color(0xFF9ECAFF)
val primaryDark = Color(0xFFD1E4FF)
val onPrimaryDark = Color(0xFF003258)
val primaryContainerDark = Color(0xFF9ECAFF)
val onPrimaryContainerDark = Color(0xFF255583)
val inversePrimaryDark = Color(0xFF336190)
val secondaryDark = Color(0xFFBBC7DB)
val onSecondaryDark = Color(0xFF263141)
val secondaryContainerDark = Color(0xFF3E4A5A)
val onSecondaryContainerDark = Color(0xFFADB9CD)
val tertiaryDark = Color(0xFFFFDDB1)
val onTertiaryDark = Color(0xFF442B00)
val tertiaryContainerDark = Color(0xFFF4BD6B)
val onTertiaryContainerDark = Color(0xFF714B00)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val primaryFixedDark = Color(0xFFD1E4FF)
val primaryFixedDimDark = Color(0xFF9ECAFF)
val onPrimaryFixedDark = Color(0xFF001D36)
val onPrimaryFixedVariantDark = Color(0xFF144977)
val secondaryFixedDark = Color(0xFFD7E3F8)
val secondaryFixedDimDark = Color(0xFFBBC7DB)
val onSecondaryFixedDark = Color(0xFF101C2B)
val onSecondaryFixedVariantDark = Color(0xFF3C4858)
val tertiaryFixedDark = Color(0xFFFFDDB1)
val tertiaryFixedDimDark = Color(0xFFF4BD6B)
val onTertiaryFixedDark = Color(0xFF291800)
val onTertiaryFixedVariantDark = Color(0xFF624000)
val backgroundDark = Color(0xFF111318)
val onBackgroundDark = Color(0xFFE2E2E9)
val surfaceVariantDark = Color(0xFF33353A)
// The documents do not specify a scrim color; use the standard black scrim.
val scrimDark = Color(0xFF000000)

// Bottom navigation colors from the light and dark HTML references.
val navigationBarContainerLight = Color(0xFFFFFFFF)
val navigationBarSelectedLight = Color(0xFF00497D)
val navigationBarIndicatorLight = Color(0xFFD7E3F8)
val navigationBarContainerDark = Color(0xFF111318)
val navigationBarSelectedDark = Color(0xFF9ECAFF)
val navigationBarIndicatorDark = Color(0xFF00497D)
